services:
  postgres:
    image: ankane/pgvector:latest   # Postgres + pgvector built-in
    container_name: pgvector_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airline_booking
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d airline_booking"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

